default_language_version:
  python: python3.9
default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       files: aigrisculteurs/src/
  #       args: [--max-line-length=199]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        files: aigrisculteurs/src/.py
