# pyproject.toml
[tool.pytest.ini_options]
minversion = "7.2.2"
addopts = "--cov=src --cov-branch --cov-report html"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = [
    "aigrisculteurs/tests"
]
